*** Variables ***
${preprod_username}    # Should set as a project/robot/suite variable from CRT UI
${preprod_password}    # Should set as a project/robot/suite variable from CRT UI
${whitespace_username}    # Should set as a project/robot/suite variable from CRT UI
${whitespace_password}    # Should set as a project/robot/suite variable from CRT UI
${c_key}        
${c_secret} 
${mfa_secret}